### ISSUE TITLE
Not clear if UnauthorizedAccessException should be fixed by the end of your process

### ISSUE THREAD

**Issue by DanBennettDev** [djkoloski/libpd64#3]
Hi,
First off - this is so very helpful, thankyou. Just one thing I'm not clear on. You say to ignore the UnauthorizedAccessException "for now" but don't return to it. Should this go away by the end of your walkthrough, or is a different fix required for this? 
(I've followed the walkthrough and still have this error)

**Comment by djkoloski** [comment]
After some investigation:

- The error should not go away
- You can comment out the contents of CheckPlugins() in PureDataPluginManager.cs safely to prevent this error

It looks like uPD is trying to copy libpdcsharp.dll into the Unity install directly in Program Files. We don't need to do that. The walkthrough will be updated.

**Comment by djkoloski** [comment]
Fixed by b12d986670e2e0e832c91c4b6832c8b4fe339cfe

**Comment by DanBennettDev** [comment]
Thanks - really helpful
